(in-package #:ems)

(defclass user () 
  ((profile-image-url-https :accessor user-profile-image-url-https :initarg :profile-image-url-https)
  (utc-offset :accessor user-utc-offset :initarg :utc-offset)
  (profile-background-image-url :accessor user-profile-background-image-url :initarg :profile-background-image-url)
  (statuses-count :accessor user-statuses-count :initarg :statuses-count)
  (status :accessor user-status :initarg :status)
  (id :accessor user-id :initarg :id)
  (location :accessor user-location :initarg :location)
  (profile-text-color :accessor user-profile-text-color :initarg :profile-text-color)
  (show-all-inline-media :accessor user-show-all-inline-media :initarg :show-all-inline-media)
  (id-str :accessor user-id-str :initarg :id-str)
  (name :accessor user-name :initarg :name)
  (profile-use-background-image :accessor user-profile-use-background-image :initarg :profile-use-background-image)
  (protected :accessor user-protected :initarg :protected)
  (friends-count :accessor user-friends-count :initarg :friends-count)
  (profile-image-url :accessor user-profile-image-url :initarg :profile-image-url)
  (followers-count :accessor user-followers-count :initarg :followers-count)
  (profile-sidebar-fill-color :accessor user-profile-sidebar-fill-color :initarg :profile-sidebar-fill-color)
  (description :accessor user-description :initarg :description)
  (time-zone :accessor user-time-zone :initarg :time-zone)
  (profile-background-tile :accessor user-profile-background-tile :initarg :profile-background-tile)
  (following :accessor user-following :initarg :following)
  (is-translator :accessor user-is-translator :initarg :is-translator)
  (profile-background-color :accessor user-profile-background-color :initarg :profile-background-color)
  (default-profile :accessor user-default-profile :initarg :default-profile)
  (profile-link-color :accessor user-profile-link-color :initarg :profile-link-color)
  (lang :accessor user-lang :initarg :lang)
  (listed-count :accessor user-listed-count :initarg :listed-count)
  (created-at :accessor user-created-at :initarg :created-at)
  (default-profile-image :accessor user-default-profile-image :initarg :default-profile-image)
  (contributors-enabled :accessor user-contributors-enabled :initarg :contributors-enabled)
  (verified :accessor user-verified :initarg :verified)
  (geo-enabled :accessor user-geo-enabled :initarg :geo-enabled)
  (profile-sidebar-border-color :accessor user-profile-sidebar-border-color :initarg :profile-sidebar-border-color)
  (url :accessor user-url :initarg :url)
  (screen-name :accessor user-screen-name :initarg :screen-name)
  (follow-request-sent :accessor user-follow-request-sent :initarg :follow-request-sent)
  (notifications :accessor user-notifications :initarg :notifications)
  (profile-background-image-url-https :accessor user-profile-background-image-url-https :initarg :profile-background-image-url-https)
  (favourites-count :accessor user-favourites-count :initarg :favourites-count)))

(defclass retweeted-status ()
  ((truncated :accessor retweeted-status-truncated :initarg :truncated)
  (in-reply-to-status-id-str :accessor retweeted-status-in-reply-to-status-id-str :initarg :in-reply-to-status-id-str)
  (id :accessor retweeted-status-id :initarg :id)
  (user :accessor retweeted-status-user :initarg :user)
  (id-str :accessor retweeted-status-id-str :initarg :id-str)
  (in-reply-to-status-id :accessor retweeted-status-in-reply-to-status-id :initarg :in-reply-to-status-id)
  (possibly-sensitive :accessor retweeted-status-possibly-sensitive :initarg :possibly-sensitive)
  (retweeted :accessor retweeted-status-retweeted :initarg :retweeted)
  (possibly-sensitive-editable :accessor retweeted-status-possibly-sensitive-editable :initarg :possibly-sensitive-editable)
  (entities :accessor retweeted-status-entities :initarg :entities)
  (favorited :accessor retweeted-status-favorited :initarg :favorited)
  (text :accessor retweeted-status-text :initarg :text)
  (in-reply-to-user-id-str :accessor retweeted-status-in-reply-to-user-id-str :initarg :in-reply-to-user-id-str)
  (place :accessor retweeted-status-place :initarg :place)
  (coordinates :accessor retweeted-status-coordinates :initarg :coordinates)
  (geo :accessor retweeted-status-geo :initarg :geo)
  (in-reply-to-screen-name :accessor retweeted-status-in-reply-to-screen-name :initarg :in-reply-to-screen-name)
  (contributors :accessor retweeted-status-contributors :initarg :contributors)
  (source :accessor retweeted-status-source :initarg :source)
  (retweet-count :accessor retweeted-status-retweet-count :initarg :retweet-count)
  (in-reply-to-user-id :accessor retweeted-status-in-reply-to-user-id :initarg :in-reply-to-user-id)
  (created-at :accessor retweeted-status-created-at :initarg :created-at)))

(defclass user-mentions ()
  ((id :accessor user-mentions-id :initarg :id)
  (id-str :accessor user-mentions-id-str :initarg :id-str)
  (name :accessor user-mentions-name :initarg :name)
  (screen-name :accessor user-mentions-screen-name :initarg :screen-name)
  (indices :accessor user-mentions-indices :initarg :indices)))

(defclass urls()
  ((display-url :accessor urls-display-url :initarg :display-url)
  (url :accessor urls-url :initarg :url)
  (expanded-url :accessor urls-expanded-url :initarg :expanded-url)
  (indices :accessor urls-indices :initarg :indices)))

(defclass entities()
  ((urls :accessor entities-urls :initarg :urls)
  (media :accessor entities-media :initarg :media)
  (user-mentions :accessor entities-user-mentions :initarg :user-mentions)
  (hashtags :accessor entities-hashtags :initarg :hashtags)))

(defclass hashtags()
  ((indices :accessor hashtags-indices :initarg :indices)
  (text :accessor hashtags-text :initarg :text)))

(defclass media ()
  ((display-url :accessor media-display-url :initarg :display-url)
  (media-url-https :accessor media-media-url-https :initarg :media-url-https)
  (id-str :accessor media-id-str :initarg :id-str)
  (id :accessor media-id :initarg :id)
  (sizes :accessor media-sizes :initarg :sizes)
  (url :accessor media-url :initarg :url)
  (media-url :accessor media-media-url :initarg :media-url)
  (expanded-url :accessor media-expanded-url :initarg :expanded-url)
  (indices :accessor media-indices :initarg :indices)
  (type :accessor media-type :initarg :type)))

(defclass sizes ()
  ((large :accessor sizes-large :initarg :large)
  (medium :accessor sizes-medium :initarg :medium)
  (thumb :accessor sizes-thumb :initarg :thumb)
  (small :accessor sizes-small :initarg :small)))

(defclass large ()
  ((w :accessor large-w :initarg :w)
  (resize :accessor large-resize :initarg :resize)
  (h :accessor large-h :initarg :h)))

(defclass medium ()
  ((w :accessor medium-w :initarg :w)
  (resize :accessor medium-resize :initarg :resize)
  (h :accessor medium-h :initarg :h)))

(defclass thumb ()
  ((w :accessor thumb-w :initarg :w)
  (resize :accessor thumb-resize :initarg :resize)
  (h :accessor thumb-h :initarg :h)))

(defclass small ()
  ((w :accessor small-w :initarg :w)
  (resize :accessor small-resize :initarg :resize)
  (h :accessor small-h :initarg :h)))

(defclass attributes ()
  ((street-address :accessor attributes-street-address :initarg :street-address)
  (locality :accessor attributes-locality :initarg :locality)
  (region :accessor attributes-region :initarg :region)
  (iso3 :accessor attributes-iso3 :initarg :iso3)
  (postal-code :accessor attributes-postal-code :initarg :postal-code)
  (phone :accessor attributes-phone :initarg :phone)
  (twitter :accessor attributes-twitter :initarg :twitter)
  (url :accessor attributes-url :initarg :url)
  (|app:id| :accessor attributes-|app:id| :initarg :|app:id|)))

(defclass places ()
  ((name :accessor places-name :initarg :name)
  (attributes :accessor places-attributes :initarg :attributes)
  (full-name :accessor places-full-name :initarg :full-name)
  (place-type :accessor places-place-type :initarg :place-type)
  (url :accessor places-url :initarg :url)
  (bounding-box :accessor places-bounding-box :initarg :bounding-box)
  (geometry :accessor places-geometry :initarg :geometry)
  (polylines :accessor places-polylines :initarg :polylines)
  (country :accessor places-country :initarg :country)
  (id :accessor places-id :initarg :id)
  (contained-within :accessor places-contained-within :initarg :contained-within)
  (country-code :accessor places-country-code :initarg :country-code)))

(defclass bounding-box ()
  ((coordinates :accessor bounding-box-coordinates :initarg :coordinates)
  (type :accessor bounding-box-type :initarg :type)))

(defclass contributors ()
  ((id :accessor contributors-id :initarg :id)
  (id-str :accessor contributors-id-str :initarg :id-str)
  (screen-name :accessor contributors-screen-name :initarg :screen-name)))

(defclass coordinates ()
  ((coordinates :accessor coordinates-coordinates :initarg :coordinates)
  (type :accessor coordinates-type :initarg :type)))

(defclass current-user-retweet ()
  ((id :accessor current-user-retweet-id :initarg :id)
  (id-str :accessor current-user-retweet-id-str :initarg :id-str)))

(defclass tweet (doc)
  ((contributors :accessor tweet-contributors :initarg :contributors)
  (geo :accessor tweet-geo :initarg :geo)
  (coordinates :accessor tweet-coordinates :initarg :coordinates)
  (created-at :accessor tweet-created-at :initarg :created-at)
  (current-user-retweet :accessor tweet-current-user-retweet :initarg :current-user-retweet)
  (entities :accessor tweet-entities :initarg :entities)
  (favorited :accessor tweet-favorited :initarg :favorited)
  (pid :accessor tweet-pid :initarg :pid)
  (id-str :accessor tweet-id-str :initarg :id-str)
  (in-reply-to-screen-name :accessor tweet-in-reply-to-screen-name :initarg :in-reply-to-screen-name)
  (in-reply-to-status-id :accessor tweet-in-reply-to-status-id :initarg :in-reply-to-status-id)
  (in-reply-to-status-id-str :accessor tweet-in-reply-to-status-id-str :initarg :in-reply-to-status-id-str)
  (in-reply-to-user-id :accessor tweet-in-reply-to-user-id :initarg :in-reply-to-user-id)
  (in-reply-to-user-id-str :accessor tweet-in-reply-to-user-id-str :initarg :in-reply-to-user-id-str)
  (place :accessor tweet-place :initarg :place)
  (possibly-sensitive :accessor tweet-possibly-sensitive :initarg :possibly-sensitive)
  (retweet-count :accessor tweet-retweet-count :initarg :retweet-count)
  (retweeted :accessor tweet-retweeted :initarg :retweeted)
  (source :accessor tweet-source :initarg :source)
  (text :accessor tweet-text :initarg :text)
  (truncated :accessor tweet-truncated :initarg :truncated)
  (user :accessor tweet-user :initarg :user)
  (retweeted-status :accessor tweet-retweeted-status :initarg :retweeted-status)
  (withheld-copyright :accessor tweet-withheld-copyright :initarg :withheld-copyright)
  (withheld-in-countries :accessor tweet-withheld-in-countries :initarg :withheld-in-countries)
  (withheld-scope :accessor tweet-withheld-scope :initarg :withheld-scope))
  (:metaclass storable-class))
