(in-package #:ems)

(defun parse-social-mention (mentions)
  (if (assoc :items mentions)
      (dolist (mention (assoc :items mentions))
        (make-instance 'social-mention
                       :id (assoc ':id mention)
                       :title (assoc ':title mention)
                       :link (assoc ':link mention)
                       :time-stamp (assoc ':timestamp mention)
                       :language (assoc ':language mention)
                       :image (assoc ':image mention)
                       :embeded (assoc ':embeded mention)
                       :user (assoc ':user mention)
                       :user-image (assoc ':user_image mention)
                       :user-link (assoc ':user_link mention)
                       :domain (assoc ':domain mention)
                       :source (assoc ':source mention)
                       :favicon (assoc ':favicon mention)
                       :type (assoc ':type mention)))))
