(in-package :dyb)

(defclass allsort (doc import-detail)
  ((sort :initarg :sort 
         :initform nil)
   (sort-value :initarg :sort-value 
               :initform nil
               :accessor sort-value)
   (sort-order :initarg :sort-order 
               :initform nil)   
   (alternate-sort-order :initarg :alternate-sort-order 
                         :initform nil)
   (aa-sort-order :initarg :aa-sort-order 
                  :initform nil)
   (description :initarg :description 
                :initform nil)
   (extended-description :initarg :extended-description 
                         :initform nil))
  (:metaclass storable-class)
  (:default-initargs :doc-type "allsort"))

(defun allsorts-collection ()
  (get-collection (system-db) "allsorts"))

(defun allsorts ()
  (docs (allsorts-collection)))

(defmethod doc-collection ((doc allsort))
                                        ;(break "shit?")
  (allsorts-collection))

(defun make-allsort (sort sort-value &key
                     sort-order alternate-sort-order
                     aa-sort-order description
                     extended-description)
  (make-instance 'allsort 
                 :key (list sort sort-value) 
                 :doc-type "allsort" 
                 :sort sort
                 :sort-order sort-order
                 :sort-value sort-value
                 :alternate-sort-order alternate-sort-order
                 :aa-sort-order aa-sort-order
                 :description description
                 :extended-description extended-description))

(defun get-allsort (sort value)
  (get-doc (allsorts-collection) 
           (list sort value)))

(defun find-allsorts (sort)
  (find-docs 'list
             (lambda (doc)
               (string-equal (get-val doc 'sort) sort))
             (allsorts-collection)))

(defun find-allsorts-for-select (sort)
  (let ((docs (find-docs 'list
                         (lambda (doc)
                           (and (string-equal (get-val doc 'sort) sort)
                                (string-not-equal (get-val doc 'doc-status) "superseded")))
                         (allsorts-collection)))
        (data))
    (dolist (doc docs)
      (setf data (append data (list (list (get-val doc 'sort-value)
                                          (get-val doc 'description))))))
    data))

(defun get-sorted-allsorts (sort)
  (let ((docs (find-docs 'list
                         (lambda (doc)
                           (and (string-equal (get-val doc 'sort) sort)
                                (string-not-equal (get-val doc 'doc-status) "superseded")))
                         (allsorts-collection)))
        (data))
    
    (dolist (doc docs)
      (setf data (append data (list (get-val doc 'sort-value)))))
    (sort  data #'STRING-LESSP)))

(defun find-allsorts-for-validation (sort)
  (let ((docs (find-docs 'list
                         (lambda (doc)
                           (and (string-equal (get-val doc 'sort) sort)
                                (string-not-equal (get-val doc 'doc-status) "superseded")))
                         (allsorts-collection)))
        (data))
    (dolist (doc docs)
      (setf data (append data (list (get-val doc 'sort-value)))))
    data))

(defun get-allsort-by-id (id)
  (get-doc (allsorts-collection) id
           :element 'xid))

(defgeneric match-allsorts (doc allsorts))

(defmethod match-allsorts (doc allsorts)
  (find (get-val doc 'xid) allsorts))

(add-collection (system-db) "allsorts" 
                :collection-class 'dyb-collection
                :load-from-file-p t)
(when (= (length (allsorts)) 0)
  (persist (make-allsort "Accredited" "Yes" :description "Yes" :extended-description ""))
  (persist (make-allsort "Accredited" "No" :description "No" :extended-description ""))
  (persist (make-allsort "Action Status" "Not Started" :description "Not Started" :extended-description ""))
  (persist (make-allsort "Action Status" "Started" :description "Started" :extended-description ""))
  (persist (make-allsort "Action Status" "Completed" :description "Completed" :extended-description ""))
  (persist (make-allsort "Action Status" "Aborted" :description "Aborted" :extended-description ""))
  (persist (make-allsort "BEE Status" "Black Empowered (BE: 25% - 50%)" :description "Black Empowered (BE: 25% - 50%)" :extended-description ""))
  (persist (make-allsort "BEE Status" "Black Influenced (BI: 5% - 25%)" :description "Black Influenced (BI: 5% - 25%)" :extended-description ""))
  (persist (make-allsort "BEE Status" "Black Owned (BO: >50%)" :description "Black Owned (BO: >50%)" :extended-description ""))
  (persist (make-allsort "BEE Status" "Empowering Supplier (ES: <5%)" :description "Empowering Supplier (ES: <5%)" :extended-description ""))
  (persist (make-allsort "Biographical Address Type" "Home Address" :description "Home Address" :extended-description ""))
  (persist (make-allsort "Biographical Address Type" "Postal Address" :description "Postal Address" :extended-description ""))
  (persist (make-allsort "Biographical Address Type" "Physical Address" :description "Physical Address" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Entity" :description "Entity" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Employee Nnumber" :description "Employee Nnumber" :extended-description ""))
  (persist (make-allsort "Biographical Import" "ID Number" :description "ID Number" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Surname" :description "Surname" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Name" :description "Name" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Gender" :description "Gender" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Race" :description "Race" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Nationality" :description "Nationality" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Country" :description "Country" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Province" :description "Province" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Town" :description "Town" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Occupational Category" :description "Occupational Category" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Occupational Level" :description "Occupational Level" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Disabled" :description "Disabled" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Employment Type" :description "Employment Type" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Job Title" :description "Job Title" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Education Level" :description "Education Level" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Housing Status" :description "Housing Status" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Date Of Birth" :description "Date Of Birth" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Date Of Engagement" :description "Date Of Engagement" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Date Of Termination" :description "Date Of Termination" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Termination Reason" :description "Termination Reason" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Effective Start Date" :description "Effective Start Date" :extended-description ""))
  (persist (make-allsort "Biographical Import" "Effective End Date" :description "Effective End Date" :extended-description ""))
  (persist (make-allsort "Broad Based BEE" "B-BBEE Recognition Level of 135% (Level 1)" :description "B-BBEE Recognition Level of 135% (Level 1)" :extended-description ""))
  (persist (make-allsort "Broad Based BEE" "B-BBEE Recognition Level of 125% (Level 2)" :description "B-BBEE Recognition Level of 125% (Level 2)" :extended-description ""))
  (persist (make-allsort "Broad Based BEE" "B-BBEE Recognition Level of 110% (Level 3)" :description "B-BBEE Recognition Level of 110% (Level 3)" :extended-description ""))
  (persist (make-allsort "Broad Based BEE" "B-BBEE Recognition Level of 100% (Level 4)" :description "B-BBEE Recognition Level of 100% (Level 4)" :extended-description ""))
  (persist (make-allsort "Broad Based BEE" "B-BBEE Recognition Level of 80% (Level 5)" :description "B-BBEE Recognition Level of 80% (Level 5)" :extended-description ""))
  (persist (make-allsort "Broad Based BEE" "B-BBEE Recognition Level of 60% (Level 6)" :description "B-BBEE Recognition Level of 60% (Level 6)" :extended-description ""))
  (persist (make-allsort "Broad Based BEE" "B-BBEE Recognition Level of 50% (Level 7)" :description "B-BBEE Recognition Level of 50% (Level 7)" :extended-description ""))
  (persist (make-allsort "Broad Based BEE" "B-BBEE Recognition Level of 10% (Level 8)" :description "B-BBEE Recognition Level of 10% (Level 8)" :extended-description ""))
  (persist (make-allsort "Broad Based BEE" "B-BBEE Recognition Level of 0% (Non - Compliant)" :description "B-BBEE Recognition Level of 0% (Non - Compliant)" :extended-description ""))
  (persist (make-allsort "Community Relevant Undertaking" "ABET Community" :description "ABET Community" :extended-description ""))
  (persist (make-allsort "Community Relevant Undertaking" "Bursaries" :description "Bursaries" :extended-description ""))
  (persist (make-allsort "Community Relevant Undertaking" "Internships" :description "Internships" :extended-description ""))
  (persist (make-allsort "Community Relevant Undertaking" "Learnerships" :description "Learnerships" :extended-description ""))
  (persist (make-allsort "Community Relevant Undertaking" "Mentoring" :description "Mentoring" :extended-description ""))
  (persist (make-allsort "Community Relevant Undertaking" "Portable Skills Training" :description "Portable Skills Training" :extended-description ""))
  (persist (make-allsort "Community Relevant Undertaking" "Preferential Procurement - HDSA" :description "Preferential Procurement - HDSA" :extended-description ""))
  (persist (make-allsort "Community Relevant Undertaking" "Preferential Procurement - Local" :description "Preferential Procurement - Local" :extended-description ""))
  (persist (make-allsort "Community Relevant Undertaking" "SMME Mentoring" :description "SMME Mentoring" :extended-description ""))
  (persist (make-allsort "Core Mining" "Yes" :description "Yes" :extended-description ""))
  (persist (make-allsort "Core Mining" "No" :description "No" :extended-description ""))
  (persist (make-allsort "Courses Import" "Entity" :description "Entity" :extended-description ""))
  (persist (make-allsort "Courses Import" "Category Id" :description "Category Id" :extended-description ""))
  (persist (make-allsort "Courses Import" "Name" :description "Name" :extended-description ""))
  (persist (make-allsort "Courses Import" "Mentorship" :description "Mentorship" :extended-description ""))
  (persist (make-allsort "Courses Import" "Level" :description "Level" :extended-description ""))
  (persist (make-allsort "Courses Import" "Accredited" :description "Accredited" :extended-description ""))
  (persist (make-allsort "Courses Import" "Length" :description "Length" :extended-description ""))
  (persist (make-allsort "Courses Import" "Effective Start Date" :description "Effective Start Date" :extended-description ""))
  (persist (make-allsort "Courses Import" "Effective End Date" :description "Effective End Date" :extended-description ""))
  (persist (make-allsort "Course Status" "Busy" :description "Busy" :extended-description ""))
  (persist (make-allsort "Course Status" "Dropped Out" :description "Dropped Out" :extended-description ""))
  (persist (make-allsort "Course Status" "Failed" :description "Failed" :extended-description ""))
  (persist (make-allsort "Course Status" "Passed" :description "Passed" :extended-description ""))
  (persist (make-allsort "Course Types" "ABET" :description "ABET" :extended-description ""))
  (persist (make-allsort "Course Types" "ABET Community" :description "ABET Community" :extended-description ""))
  (persist (make-allsort "Course Types" "Bursaries" :description "Bursaries" :extended-description ""))
  (persist (make-allsort "Course Types" "Career Progression Plans" :description "Career Progression Plans" :extended-description ""))
  (persist (make-allsort "Course Types" "Core Business Skills Training" :description "Core Business Skills Training" :extended-description ""))
  (persist (make-allsort "Course Types" "Graduate Development Programme" :description "Graduate Development Programme" :extended-description ""))
  (persist (make-allsort "Course Types" "Internships" :description "Internships" :extended-description ""))
  (persist (make-allsort "Course Types" "Learnerships" :description "Learnerships" :extended-description ""))
  (persist (make-allsort "Course Types" "Portable Skills Training" :description "Portable Skills Training" :extended-description ""))
  (persist (make-allsort "Course Types" "Portable Skills Training (Non Mining)" :description "Portable Skills Training (Non Mining)" :extended-description ""))
  (persist (make-allsort "Disabled" "Yes" :description "Yes" :extended-description ""))
  (persist (make-allsort "Disabled" "No" :description "No" :extended-description ""))
  (persist (make-allsort "Discretionary Spend" "No" :description "No" :extended-description ""))
  (persist (make-allsort "Discretionary Spend" "Yes" :description "Yes" :extended-description ""))
  (persist (make-allsort "Downscaling & Retrenchment Undertaking" "Establishment of Future Forum" :description "Establishment of Future Forum" :extended-description ""))
  (persist (make-allsort "Downscaling & Retrenchment Undertaking" "Mechanisms to Ameliorate Socio-Economic Impact" :description "Mechanisms to Ameliorate Socio-Economic Impact" :extended-description ""))
  (persist (make-allsort "Downscaling & Retrenchment Undertaking" "Mechanisms to Avoid Job Losses" :description "Mechanisms to Avoid Job Losses" :extended-description ""))
  (persist (make-allsort "Downscaling & Retrenchment Undertaking" "Provision of Alternative Solutions" :description "Provision of Alternative Solutions" :extended-description ""))
  (persist (make-allsort "Education Level" "Diplomas/Certificates" :description "Diplomas/Certificates" :extended-description ""))
  (persist (make-allsort "Education Level" "Doctorates" :description "Doctorates" :extended-description ""))
  (persist (make-allsort "Education Level" "First Degrees/Higher Diplomas" :description "First Degrees/Higher Diplomas" :extended-description ""))
  (persist (make-allsort "Education Level" "Grade 0/Pre" :description "Grade 0/Pre" :extended-description ""))
  (persist (make-allsort "Education Level" "Grade 10/Std 8/N1" :description "Grade 10/Std 8/N1" :extended-description ""))
  (persist (make-allsort "Education Level" "Grade 11/Std 9/N2" :description "Grade 11/Std 9/N2" :extended-description ""))
  (persist (make-allsort "Education Level" "Grade 12/Std 10/N3" :description "Grade 12/Std 10/N3" :extended-description ""))
  (persist (make-allsort "Education Level" "Grade 1/Sub A" :description "Grade 1/Sub A" :extended-description ""))
  (persist (make-allsort "Education Level" "Grade 2/Sub B" :description "Grade 2/Sub B" :extended-description ""))
  (persist (make-allsort "Education Level" "Grade 3/Std 1/ABET 1" :description "Grade 3/Std 1/ABET 1" :extended-description ""))
  (persist (make-allsort "Education Level" "Grade 4/Std 2" :description "Grade 4/Std 2" :extended-description ""))
  (persist (make-allsort "Education Level" "Grade 5/Std 3/ABET 2" :description "Grade 5/std3/ABET 2" :extended-description ""))
  (persist (make-allsort "Education Level" "Grade 6/Std 4" :description "Grade 6/Std 4" :extended-description ""))
  (persist (make-allsort "Education Level" "Grade 7/Std 5/ABET 3" :description "Grade7/Std 5 ABET 3" :extended-description ""))
  (persist (make-allsort "Education Level" "Grade 8/Std 6" :description "Grade 8/Std 6" :extended-description ""))
  (persist (make-allsort "Education Level" "Grade 9/Std 7/ABET 4" :description "Grade 9/Std 7/ABET 4" :extended-description ""))
  (persist (make-allsort "Education Level" "Honors/Masters Degrees" :description "Honors/Masters Degrees" :extended-description ""))
  (persist (make-allsort "Education Level" "No Schooling" :description "No Schooling" :extended-description ""))
  (persist (make-allsort "Employee Course Import" "Course ID" :description "Course ID" :extended-description ""))
  (persist (make-allsort "Employee Course Import" "Employee Number" :description "Employee Number" :extended-description ""))
  (persist (make-allsort "Employee Course Import" "Mentor" :description "Mentor" :extended-description ""))
  (persist (make-allsort "Employee Course Import" "Status" :description "Status" :extended-description ""))
  (persist (make-allsort "Employee Course Import" "Start Date" :description "Start Date" :extended-description ""))
  (persist (make-allsort "Employee Course Import" "End Date" :description "End Date" :extended-description ""))
  (persist (make-allsort "Employee Course Import" "Effective Start Date" :description "Effective Start Date" :extended-description ""))
  (persist (make-allsort "Employee Course Import" "Effective End Date" :description "Effective End Date" :extended-description ""))
  (persist (make-allsort "Employment Type" "Non Employee" :description "Non Employee" :extended-description ""))
  (persist (make-allsort "Employment Type" "Non Permanent" :description "Non Permanent" :extended-description ""))
  (persist (make-allsort "Employment Type" "Permanent" :description "Permanent" :extended-description ""))
  (persist (make-allsort "Entity Type" "Community" :description "Community" :extended-description ""))
  (persist (make-allsort "Entity Type" "Contractor" :description "Contractor" :extended-description ""))
  (persist (make-allsort "Entity Type" "Mine" :description "Mine" :extended-description ""))
  (persist (make-allsort "Feedback Level" "Undertaking" :description "Undertaking" :extended-description ""))
  (persist (make-allsort "Feedback Level" "Undertaking Target" :description "Undertaking Target" :extended-description ""))
  (persist (make-allsort "Feedback Level" "Undertaking Action" :description "Undertaking Action" :extended-description ""))
  (persist (make-allsort "Feedback Level" "Undertaking Strategy" :description "Undertaking Strategy" :extended-description ""))
  (persist (make-allsort "Feedback Level" "LED Project" :description "LED Project" :extended-description ""))
  (persist (make-allsort "Feedback Level" "LED Project Action" :description "LED Project Action" :extended-description ""))
  (persist (make-allsort "Financial Provision Undertaking" "Financial Provision - Downscaling & Retrenchment" :description "Financial Provision - Downscaling & Retrenchment" :extended-description ""))
  (persist (make-allsort "Financial Provision Undertaking" "Financial Provision - HRD" :description "Financial Provision - HRD" :extended-description ""))
  (persist (make-allsort "Financial Provision Undertaking" "Financial Provision - LED" :description "Financial Provision - LED" :extended-description ""))
  (persist (make-allsort "Financial Provision Undertaking" "SLP Communication Strategy" :description "SLP Communication Strategy" :extended-description ""))
  (persist (make-allsort "Forum Frequency Unit" "Day" :description "Per Day" :extended-description ""))
  (persist (make-allsort "Forum Frequency Unit" "Month" :description "Per Month" :extended-description ""))
  (persist (make-allsort "Forum Frequency Unit" "Year" :description "Per Year" :extended-description ""))
  (persist (make-allsort "Gender" "Female" :description "Female" :extended-description ""))
  (persist (make-allsort "Gender" "Male" :description "Male" :extended-description ""))
  (persist (make-allsort "HDSA Target" "D - Designated - Other" :description "D - Designated - Other" :extended-description ""))
  (persist (make-allsort "HDSA Target" "D - Designated - White Female" :description "D - Designated - White Female" :extended-description ""))
  (persist (make-allsort "HDSA Target" "D - Non-Designated" :description "D - Non-Designated" :extended-description ""))
  (persist (make-allsort "HDSA Target" "E - Designated - Other" :description "E - Designated - Other" :extended-description ""))
  (persist (make-allsort "HDSA Target" "E - Designated - White Female" :description "E - Designated - White Female" :extended-description ""))
  (persist (make-allsort "HDSA Target" "E - Non-Designated" :description "E - Non-Designated" :extended-description ""))
  (persist (make-allsort "HDSA Target" "F - Designated - Other" :description "F - Designated - Other" :extended-description ""))
  (persist (make-allsort "HDSA Target" "F - Designated - White Female" :description "F - Designated - White Female" :extended-description ""))
  (persist (make-allsort "HDSA Target" "F - Non-Designated" :description "F - Non-Designated" :extended-description ""))
  (persist (make-allsort "Housing Status" "Home Owner" :description "Home Owner" :extended-description ""))
  (persist (make-allsort "Housing Status" "Mine Rental - Family Quarters" :description "Mine Rental - Family Quarters" :extended-description ""))
  (persist (make-allsort "Housing Status" "Mine Rental - Mine House" :description "Mine Rental - Mine House" :extended-description ""))
  (persist (make-allsort "Housing Status" "Mine Rental - Single Quarters" :description "Mine Rental - Single Quarters" :extended-description ""))
  (persist (make-allsort "Housing Status" "Rental (Own Initiative)" :description "Rental (Own Initiative)" :extended-description ""))
  (persist (make-allsort "Housing Status" "Stay with Parents" :description "Stay with Parents" :extended-description ""))
  (persist (make-allsort "HRD Undertaking" "ABET" :description "ABET" :extended-description ""))
  (persist (make-allsort "HRD Undertaking" "Bursaries" :description "Bursaries" :extended-description ""))
  (persist (make-allsort "HRD Undertaking" "Career Progression Plans" :description "Career Progression Plans" :extended-description ""))
  (persist (make-allsort "HRD Undertaking" "Core Business Skills Training" :description "Core Business Skills Training" :extended-description ""))
  (persist (make-allsort "HRD Undertaking" "Employment Equity" :description "Employment Equity" :extended-description ""))
  (persist (make-allsort "HRD Undertaking" "HDSA In Management" :description "HDSA In Management" :extended-description ""))
  (persist (make-allsort "HRD Undertaking" "Internships" :description "Internships" :extended-description ""))
  (persist (make-allsort "HRD Undertaking" "Learnerships" :description "Learnerships" :extended-description ""))
  (persist (make-allsort "HRD Undertaking" "Mentoring" :description "Mentoring" :extended-description ""))
  (persist (make-allsort "HRD Undertaking" "Portable Skills Training" :description "Portable Skills Training" :extended-description ""))
  (persist (make-allsort "HRD Undertaking" "Skills Development" :description "Skills Development" :extended-description ""))
  (persist (make-allsort "HRD Undertaking" "SMME Mentoring" :description "SMME Mentoring" :extended-description ""))
  (persist (make-allsort "HRD Undertaking" "Women In Mining" :description "Women In Mining" :extended-description ""))
  (persist (make-allsort "Job Title Import" "Entity" :description "Entity" :extended-description ""))
  (persist (make-allsort "Job Title Import" "Job Title" :description "Job Title" :extended-description ""))
  (persist (make-allsort "Job Title Import" "Description" :description "Description" :extended-description ""))
  (persist (make-allsort "Job Title Import" "Core Mining" :description "Core Mining" :extended-description ""))
  (persist (make-allsort "Job Title Import" "Occupational Level" :description "Occupational Level" :extended-description ""))
  (persist (make-allsort "Job Title Import" "Effective Start Date" :description "Effective Start Date" :extended-description ""))
  (persist (make-allsort "Job Title Import" "Effective End Date" :description "Effective End Date" :extended-description ""))
  (persist (make-allsort "Labour Sending Areas" "Foreign Migrancy" :description "Foreign Migrancy" :extended-description ""))
  (persist (make-allsort "Labour Sending Areas" "In Province Migrancy" :description "In Province Migrancy" :extended-description ""))
  (persist (make-allsort "Labour Sending Areas" "Inter Provincial Migrancy" :description "Inter Provincial Migrancy" :extended-description ""))
  (persist (make-allsort "Labour Sending Areas" "Local (< 50km)" :description "Local (< 50km)" :extended-description ""))
  (persist (make-allsort "LED Undertaking" "Housing Strategy" :description "Housing Strategy" :extended-description ""))
  (persist (make-allsort "LED Undertaking" "Local Economic Development" :description "Local Economic Development" :extended-description ""))
  (persist (make-allsort "LED Undertaking" "Nutrition" :description "Nutrition" :extended-description ""))
  (persist (make-allsort "LED Undertaking" "Preferential Procurement - HDSA" :description "Preferential Procurement - HDSA" :extended-description ""))
  (persist (make-allsort "LED Undertaking" "Preferential Procurement - Local" :description "Preferential Procurement - Local" :extended-description ""))
  (persist (make-allsort "Mentoring Course Types" "Bursaries" :description "Bursaries" :extended-description ""))
  (persist (make-allsort "Mentoring Course Types" "Internships" :description "Internships" :extended-description ""))
  (persist (make-allsort "Mentoring Course Types" "Learnerships" :description "Learnerships" :extended-description ""))
  (persist (make-allsort "Mentorship" "Yes" :description "Yes" :extended-description ""))
  (persist (make-allsort "Mentorship" "No" :description "No" :extended-description ""))
  (persist (make-allsort "Multinational" "No" :description "No" :extended-description ""))
  (persist (make-allsort "Multinational" "Yes" :description "Yes" :extended-description ""))
  (persist (make-allsort "Narrow Based BEE" "Empowering Supplier (ES: 1% - 5%)" :description "Empowering Supplier (ES: 1% - 5%)" :extended-description ""))
  (persist (make-allsort "Narrow Based BEE" "Black Influenced (BI: 5% - 25%)" :description "Black Influenced (BI: 5% - 25%)" :extended-description ""))
  (persist (make-allsort "Narrow Based BEE" "Black Empowered (BE: 25% - 50%)" :description "Black Empowered (BE: 25% - 50%)" :extended-description ""))
  (persist (make-allsort "Narrow Based BEE" "Black Owned (BO: >50%)" :description "Black Owned (BO: >50%)" :extended-description ""))
  (persist (make-allsort "Narrow Based BEE" "Woman Empowered (WE: %)" :description "Woman Empowered (WF: %)" :extended-description ""))
  (persist (make-allsort "Narrow Based BEE" "Non - Compliant (NC: = 0%)" :description "Non - Compliant (NC: = 0%)" :extended-description ""))
  (persist (make-allsort "Nationality" "Afghan" :description "Afghan" :extended-description ""))
  (persist (make-allsort "Nationality" "Albanian" :description "Albanian" :extended-description ""))
  (persist (make-allsort "Nationality" "Algerian" :description "Algerian" :extended-description ""))
  (persist (make-allsort "Nationality" "American" :description "American" :extended-description ""))
  (persist (make-allsort "Nationality" "Andorran" :description "Andorran" :extended-description ""))
  (persist (make-allsort "Nationality" "Angolan" :description "Angolan" :extended-description ""))
  (persist (make-allsort "Nationality" "Antiguans" :description "Antiguans" :extended-description ""))
  (persist (make-allsort "Nationality" "Argentinean" :description "Argentinean" :extended-description ""))
  (persist (make-allsort "Nationality" "Armenian" :description "Armenian" :extended-description ""))
  (persist (make-allsort "Nationality" "Australian" :description "Australian" :extended-description ""))
  (persist (make-allsort "Nationality" "Austrian" :description "Austrian" :extended-description ""))
  (persist (make-allsort "Nationality" "Azerbaijani" :description "Azerbaijani" :extended-description ""))
  (persist (make-allsort "Nationality" "Bahamian" :description "Bahamian" :extended-description ""))
  (persist (make-allsort "Nationality" "Bahraini" :description "Bahraini" :extended-description ""))
  (persist (make-allsort "Nationality" "Bangladeshi" :description "Bangladeshi" :extended-description ""))
  (persist (make-allsort "Nationality" "Barbadian" :description "Barbadian" :extended-description ""))
  (persist (make-allsort "Nationality" "Barbudans" :description "Barbudans" :extended-description ""))
  (persist (make-allsort "Nationality" "Batswana" :description "Batswana" :extended-description ""))
  (persist (make-allsort "Nationality" "Belarusian" :description "Belarusian" :extended-description ""))
  (persist (make-allsort "Nationality" "Belgian" :description "Belgian" :extended-description ""))
  (persist (make-allsort "Nationality" "Belizean" :description "Belizean" :extended-description ""))
  (persist (make-allsort "Nationality" "Beninese" :description "Beninese" :extended-description ""))
  (persist (make-allsort "Nationality" "Bhutanese" :description "Bhutanese" :extended-description ""))
  (persist (make-allsort "Nationality" "Bolivian" :description "Bolivian" :extended-description ""))
  (persist (make-allsort "Nationality" "Bosnian" :description "Bosnian" :extended-description ""))
  (persist (make-allsort "Nationality" "Brazilian" :description "Brazilian" :extended-description ""))
  (persist (make-allsort "Nationality" "British" :description "British" :extended-description ""))
  (persist (make-allsort "Nationality" "Bruneian" :description "Bruneian" :extended-description ""))
  (persist (make-allsort "Nationality" "Bulgarian" :description "Bulgarian" :extended-description ""))
  (persist (make-allsort "Nationality" "Burkinabe" :description "Burkinabe" :extended-description ""))
  (persist (make-allsort "Nationality" "Burmese" :description "Burmese" :extended-description ""))
  (persist (make-allsort "Nationality" "Burundian" :description "Burundian" :extended-description ""))
  (persist (make-allsort "Nationality" "Cambodian" :description "Cambodian" :extended-description ""))
  (persist (make-allsort "Nationality" "Cameroonian" :description "Cameroonian" :extended-description ""))
  (persist (make-allsort "Nationality" "Canadian" :description "Canadian" :extended-description ""))
  (persist (make-allsort "Nationality" "Cape Verdean" :description "Cape Verdean" :extended-description ""))
  (persist (make-allsort "Nationality" "Central African" :description "Central African" :extended-description ""))
  (persist (make-allsort "Nationality" "Chadian" :description "Chadian" :extended-description ""))
  (persist (make-allsort "Nationality" "Chilean" :description "Chilean" :extended-description ""))
  (persist (make-allsort "Nationality" "Chinese" :description "Chinese" :extended-description ""))
  (persist (make-allsort "Nationality" "Colombian" :description "Colombian" :extended-description ""))
  (persist (make-allsort "Nationality" "Comoran" :description "Comoran" :extended-description ""))
  (persist (make-allsort "Nationality" "Congolese" :description "Congolese" :extended-description ""))
  (persist (make-allsort "Nationality" "Costa Rican" :description "Costa Rican" :extended-description ""))
  (persist (make-allsort "Nationality" "Croatian" :description "Croatian" :extended-description ""))
  (persist (make-allsort "Nationality" "Cuban" :description "Cuban" :extended-description ""))
  (persist (make-allsort "Nationality" "Cypriot" :description "Cypriot" :extended-description ""))
  (persist (make-allsort "Nationality" "Czech" :description "Czech" :extended-description ""))
  (persist (make-allsort "Nationality" "Danish" :description "Danish" :extended-description ""))
  (persist (make-allsort "Nationality" "Djibouti" :description "Djibouti" :extended-description ""))
  (persist (make-allsort "Nationality" "Dominican" :description "Dominican" :extended-description ""))
  (persist (make-allsort "Nationality" "Dutch" :description "Dutch" :extended-description ""))
  (persist (make-allsort "Nationality" "East Timorese" :description "East Timorese" :extended-description ""))
  (persist (make-allsort "Nationality" "Ecuadorean" :description "Ecuadorean" :extended-description ""))
  (persist (make-allsort "Nationality" "Egyptian" :description "Egyptian" :extended-description ""))
  (persist (make-allsort "Nationality" "Emirian" :description "Emirian" :extended-description ""))
  (persist (make-allsort "Nationality" "Equatorial Guinean" :description "Equatorial Guinean" :extended-description ""))
  (persist (make-allsort "Nationality" "Eritrean" :description "Eritrean" :extended-description ""))
  (persist (make-allsort "Nationality" "Estonian" :description "Estonian" :extended-description ""))
  (persist (make-allsort "Nationality" "Ethiopian" :description "Ethiopian" :extended-description ""))
  (persist (make-allsort "Nationality" "Fijian" :description "Fijian" :extended-description ""))
  (persist (make-allsort "Nationality" "Filipino" :description "Filipino" :extended-description ""))
  (persist (make-allsort "Nationality" "Finnish" :description "Finnish" :extended-description ""))
  (persist (make-allsort "Nationality" "French" :description "French" :extended-description ""))
  (persist (make-allsort "Nationality" "Gabonese" :description "Gabonese" :extended-description ""))
  (persist (make-allsort "Nationality" "Gambian" :description "Gambian" :extended-description ""))
  (persist (make-allsort "Nationality" "Georgian" :description "Georgian" :extended-description ""))
  (persist (make-allsort "Nationality" "German" :description "German" :extended-description ""))
  (persist (make-allsort "Nationality" "Ghanaian" :description "Ghanaian" :extended-description ""))
  (persist (make-allsort "Nationality" "Greek" :description "Greek" :extended-description ""))
  (persist (make-allsort "Nationality" "Grenadian" :description "Grenadian" :extended-description ""))
  (persist (make-allsort "Nationality" "Guatemalan" :description "Guatemalan" :extended-description ""))
  (persist (make-allsort "Nationality" "Guinea-Bissauan" :description "Guinea-Bissauan" :extended-description ""))
  (persist (make-allsort "Nationality" "Guinean" :description "Guinean" :extended-description ""))
  (persist (make-allsort "Nationality" "Guyanese" :description "Guyanese" :extended-description ""))
  (persist (make-allsort "Nationality" "Haitian" :description "Haitian" :extended-description ""))
  (persist (make-allsort "Nationality" "Herzegovinian" :description "Herzegovinian" :extended-description ""))
  (persist (make-allsort "Nationality" "Honduran" :description "Honduran" :extended-description ""))
  (persist (make-allsort "Nationality" "Hungarian" :description "Hungarian" :extended-description ""))
  (persist (make-allsort "Nationality" "I-Kiribati" :description "I-Kiribati" :extended-description ""))
  (persist (make-allsort "Nationality" "Icelander" :description "Icelander" :extended-description ""))
  (persist (make-allsort "Nationality" "Indian" :description "Indian" :extended-description ""))
  (persist (make-allsort "Nationality" "Indonesian" :description "Indonesian" :extended-description ""))
  (persist (make-allsort "Nationality" "Iranian" :description "Iranian" :extended-description ""))
  (persist (make-allsort "Nationality" "Iraqi" :description "Iraqi" :extended-description ""))
  (persist (make-allsort "Nationality" "Irish" :description "Irish" :extended-description ""))
  (persist (make-allsort "Nationality" "Israeli" :description "Israeli" :extended-description ""))
  (persist (make-allsort "Nationality" "Italian" :description "Italian" :extended-description ""))
  (persist (make-allsort "Nationality" "Ivorian" :description "Ivorian" :extended-description ""))
  (persist (make-allsort "Nationality" "Jamaican" :description "Jamaican" :extended-description ""))
  (persist (make-allsort "Nationality" "Japanese" :description "Japanese" :extended-description ""))
  (persist (make-allsort "Nationality" "Jordanian" :description "Jordanian" :extended-description ""))
  (persist (make-allsort "Nationality" "Kazakhstani" :description "Kazakhstani" :extended-description ""))
  (persist (make-allsort "Nationality" "Kenyan" :description "Kenyan" :extended-description ""))
  (persist (make-allsort "Nationality" "Kittian and Nevisian" :description "Kittian and Nevisian" :extended-description ""))
  (persist (make-allsort "Nationality" "Kuwaiti" :description "Kuwaiti" :extended-description ""))
  (persist (make-allsort "Nationality" "Kyrgyz" :description "Kyrgyz" :extended-description ""))
  (persist (make-allsort "Nationality" "Laotian" :description "Laotian" :extended-description ""))
  (persist (make-allsort "Nationality" "Latvian" :description "Latvian" :extended-description ""))
  (persist (make-allsort "Nationality" "Lebanese" :description "Lebanese" :extended-description ""))
  (persist (make-allsort "Nationality" "Liberian" :description "Liberian" :extended-description ""))
  (persist (make-allsort "Nationality" "Libyan" :description "Libyan" :extended-description ""))
  (persist (make-allsort "Nationality" "Liechtensteiner" :description "Liechtensteiner" :extended-description ""))
  (persist (make-allsort "Nationality" "Lithuanian" :description "Lithuanian" :extended-description ""))
  (persist (make-allsort "Nationality" "Luxembourger" :description "Luxembourger" :extended-description ""))
  (persist (make-allsort "Nationality" "Macedonian" :description "Macedonian" :extended-description ""))
  (persist (make-allsort "Nationality" "Malagasy" :description "Malagasy" :extended-description ""))
  (persist (make-allsort "Nationality" "Malawian" :description "Malawian" :extended-description ""))
  (persist (make-allsort "Nationality" "Malaysian" :description "Malaysian" :extended-description ""))
  (persist (make-allsort "Nationality" "Maldivan" :description "Maldivan" :extended-description ""))
  (persist (make-allsort "Nationality" "Malian" :description "Malian" :extended-description ""))
  (persist (make-allsort "Nationality" "Maltese" :description "Maltese" :extended-description ""))
  (persist (make-allsort "Nationality" "Marshallese" :description "Marshallese" :extended-description ""))
  (persist (make-allsort "Nationality" "Mauritanian" :description "Mauritanian" :extended-description ""))
  (persist (make-allsort "Nationality" "Mauritian" :description "Mauritian" :extended-description ""))
  (persist (make-allsort "Nationality" "Mexican" :description "Mexican" :extended-description ""))
  (persist (make-allsort "Nationality" "Micronesian" :description "Micronesian" :extended-description ""))
  (persist (make-allsort "Nationality" "Moldovan" :description "Moldovan" :extended-description ""))
  (persist (make-allsort "Nationality" "Monacan" :description "Monacan" :extended-description ""))
  (persist (make-allsort "Nationality" "Mongolian" :description "Mongolian" :extended-description ""))
  (persist (make-allsort "Nationality" "Moroccan" :description "Moroccan" :extended-description ""))
  (persist (make-allsort "Nationality" "Mosotho" :description "Mosotho" :extended-description ""))
  (persist (make-allsort "Nationality" "Motswana" :description "Motswana" :extended-description ""))
  (persist (make-allsort "Nationality" "Mozambican" :description "Mozambican" :extended-description ""))
  (persist (make-allsort "Nationality" "Namibian" :description "Namibian" :extended-description ""))
  (persist (make-allsort "Nationality" "Nauruan" :description "Nauruan" :extended-description ""))
  (persist (make-allsort "Nationality" "Nepalese" :description "Nepalese" :extended-description ""))
  (persist (make-allsort "Nationality" "New Zealander" :description "New Zealander" :extended-description ""))
  (persist (make-allsort "Nationality" "Nicaraguan" :description "Nicaraguan" :extended-description ""))
  (persist (make-allsort "Nationality" "Nigerian" :description "Nigerian" :extended-description ""))
  (persist (make-allsort "Nationality" "Nigerien" :description "Nigerien" :extended-description ""))
  (persist (make-allsort "Nationality" "North Korean" :description "North Korean" :extended-description ""))
  (persist (make-allsort "Nationality" "Northern Irish" :description "Northern Irish" :extended-description ""))
  (persist (make-allsort "Nationality" "Norwegian" :description "Norwegian" :extended-description ""))
  (persist (make-allsort "Nationality" "Omani" :description "Omani" :extended-description ""))
  (persist (make-allsort "Nationality" "Pakistani" :description "Pakistani" :extended-description ""))
  (persist (make-allsort "Nationality" "Palauan" :description "Palauan" :extended-description ""))
  (persist (make-allsort "Nationality" "Panamanian" :description "Panamanian" :extended-description ""))
  (persist (make-allsort "Nationality" "Papua New Guinean" :description "Papua New Guinean" :extended-description ""))
  (persist (make-allsort "Nationality" "Paraguayan" :description "Paraguayan" :extended-description ""))
  (persist (make-allsort "Nationality" "Peruvian" :description "Peruvian" :extended-description ""))
  (persist (make-allsort "Nationality" "Polish" :description "Polish" :extended-description ""))
  (persist (make-allsort "Nationality" "Portuguese" :description "Portuguese" :extended-description ""))
  (persist (make-allsort "Nationality" "Qatari" :description "Qatari" :extended-description ""))
  (persist (make-allsort "Nationality" "Romanian" :description "Romanian" :extended-description ""))
  (persist (make-allsort "Nationality" "Russian" :description "Russian" :extended-description ""))
  (persist (make-allsort "Nationality" "Rwandan" :description "Rwandan" :extended-description ""))
  (persist (make-allsort "Nationality" "Saint Lucian" :description "Saint Lucian" :extended-description ""))
  (persist (make-allsort "Nationality" "Salvadoran" :description "Salvadoran" :extended-description ""))
  (persist (make-allsort "Nationality" "Samoan" :description "Samoan" :extended-description ""))
  (persist (make-allsort "Nationality" "San Marinese" :description "San Marinese" :extended-description ""))
  (persist (make-allsort "Nationality" "Sao Tomean" :description "Sao Tomean" :extended-description ""))
  (persist (make-allsort "Nationality" "Saudi" :description "Saudi" :extended-description ""))
  (persist (make-allsort "Nationality" "Scottish" :description "Scottish" :extended-description ""))
  (persist (make-allsort "Nationality" "Senegalese" :description "Senegalese" :extended-description ""))
  (persist (make-allsort "Nationality" "Serbian" :description "Serbian" :extended-description ""))
  (persist (make-allsort "Nationality" "Seychellois" :description "Seychellois" :extended-description ""))
  (persist (make-allsort "Nationality" "Sierra Leonean" :description "Sierra Leonean" :extended-description ""))
  (persist (make-allsort "Nationality" "Singaporean" :description "Singaporean" :extended-description ""))
  (persist (make-allsort "Nationality" "Slovakian" :description "Slovakian" :extended-description ""))
  (persist (make-allsort "Nationality" "Slovenian" :description "Slovenian" :extended-description ""))
  (persist (make-allsort "Nationality" "Solomon Islander" :description "Solomon Islander" :extended-description ""))
  (persist (make-allsort "Nationality" "Somali" :description "Somali" :extended-description ""))
  (persist (make-allsort "Nationality" "South African" :description "South African" :extended-description ""))
  (persist (make-allsort "Nationality" "South Korean" :description "South Korean" :extended-description ""))
  (persist (make-allsort "Nationality" "Spanish" :description "Spanish" :extended-description ""))
  (persist (make-allsort "Nationality" "Sri Lankan" :description "Sri Lankan" :extended-description ""))
  (persist (make-allsort "Nationality" "Sudanese" :description "Sudanese" :extended-description ""))
  (persist (make-allsort "Nationality" "Surinamer" :description "Surinamer" :extended-description ""))
  (persist (make-allsort "Nationality" "Swazi" :description "Swazi" :extended-description ""))
  (persist (make-allsort "Nationality" "Swedish" :description "Swedish" :extended-description ""))
  (persist (make-allsort "Nationality" "Swiss" :description "Swiss" :extended-description ""))
  (persist (make-allsort "Nationality" "Syrian" :description "Syrian" :extended-description ""))
  (persist (make-allsort "Nationality" "Taiwanese" :description "Taiwanese" :extended-description ""))
  (persist (make-allsort "Nationality" "Tajik" :description "Tajik" :extended-description ""))
  (persist (make-allsort "Nationality" "Tanzanian" :description "Tanzanian" :extended-description ""))
  (persist (make-allsort "Nationality" "Thai" :description "Thai" :extended-description ""))
  (persist (make-allsort "Nationality" "Togolese" :description "Togolese" :extended-description ""))
  (persist (make-allsort "Nationality" "Tongan" :description "Tongan" :extended-description ""))
  (persist (make-allsort "Nationality" "Trinidadian or Tobagonian" :description "Trinidadian or Tobagonian" :extended-description ""))
  (persist (make-allsort "Nationality" "Tunisian" :description "Tunisian" :extended-description ""))
  (persist (make-allsort "Nationality" "Turkish" :description "Turkish" :extended-description ""))
  (persist (make-allsort "Nationality" "Tuvaluan" :description "Tuvaluan" :extended-description ""))
  (persist (make-allsort "Nationality" "Ugandan" :description "Ugandan" :extended-description ""))
  (persist (make-allsort "Nationality" "Ukrainian" :description "Ukrainian" :extended-description ""))
  (persist (make-allsort "Nationality" "Uruguayan" :description "Uruguayan" :extended-description ""))
  (persist (make-allsort "Nationality" "Uzbekistani" :description "Uzbekistani" :extended-description ""))
  (persist (make-allsort "Nationality" "Venezuelan" :description "Venezuelan" :extended-description ""))
  (persist (make-allsort "Nationality" "Vietnamese" :description "Vietnamese" :extended-description ""))
  (persist (make-allsort "Nationality" "Welsh" :description "Welsh" :extended-description ""))
  (persist (make-allsort "Nationality" "Yemenite" :description "Yemenite" :extended-description ""))
  (persist (make-allsort "Nationality" "Zambian" :description "Zambian" :extended-description ""))
  (persist (make-allsort "Nationality" "Zimbabwean" :description "Zimbabwean" :extended-description ""))
  (persist (make-allsort "Occupational Category" "Managers" :description "Managers" :extended-description ""))
  (persist (make-allsort "Occupational Category" "Professionals" :description "Professionals" :extended-description ""))
  (persist (make-allsort "Occupational Category" "Technicians and Trades Workers" :description "Technicians and Trades Workers" :extended-description ""))
  (persist (make-allsort "Occupational Category" "Community and Personal Service Workers" :description "Community and Personal Service Workers" :extended-description ""))
  (persist (make-allsort "Occupational Category" "Clerical and Administrative workers" :description "Clerical and Administrative workers" :extended-description ""))
  (persist (make-allsort "Occupational Category" "Sales Workers" :description "Sales Workers" :extended-description ""))
  (persist (make-allsort "Occupational Category" "Machinery Operators and Drivers" :description "Machinery Operators and Drivers" :extended-description ""))
  (persist (make-allsort "Occupational Category" "Elementary Workers" :description "Elementary Workers" :extended-description ""))
  (persist (make-allsort "Occupational Level" "Paterson Level F" :description "Paterson Level F" :extended-description ""))
  (persist (make-allsort "Occupational Level" "Paterson Level E" :description "Paterson Level E" :extended-description ""))
  (persist (make-allsort "Occupational Level" "Paterson Level D" :description "Paterson Level D" :extended-description ""))
  (persist (make-allsort "Occupational Level" "Paterson Level C" :description "Paterson Level C" :extended-description ""))
  (persist (make-allsort "Occupational Level" "Paterson Level B" :description "Paterson Level B" :extended-description ""))
  (persist (make-allsort "Occupational Level" "Paterson Level A" :description "Paterson Level A" :extended-description ""))
  (persist (make-allsort "Preamble Undertaking" "ABET Community" :description "ABET Community" :extended-description ""))
  (persist (make-allsort "Preamble Undertaking" "Local Recruitment" :description "Local Recruitment" :extended-description ""))
  (persist (make-allsort "Preamble Undertaking" "Workforce Ramp Up" :description "Workforce Ramp Up" :extended-description ""))
  (persist (make-allsort "Preferential Procurement - Local" "District" :description "District" :extended-description ""))
  (persist (make-allsort "Preferential Procurement - Local" "Local" :description "Local" :extended-description ""))
  (persist (make-allsort "Preferential Procurement - Local" "National" :description "Out of Province" :extended-description ""))
  (persist (make-allsort "Preferential Procurement - Local" "Provincial" :description "Provincial" :extended-description ""))
  (persist (make-allsort "Procurement Service Rendered" "Capital" :description "Capital" :extended-description ""))
  (persist (make-allsort "Procurement Service Rendered" "Consumables" :description "Consumables" :extended-description ""))
  (persist (make-allsort "Procurement Service Rendered" "Services" :description "Services" :extended-description ""))
  (persist (make-allsort "Procurement Transactions Import" "Sup ID" :description "Sup ID" :extended-description ""))
  (persist (make-allsort "Procurement Transactions Import" "Transaction Reference" :description "Transaction Reference" :extended-description ""))
  (persist (make-allsort "Procurement Transactions Import" "Service Rendered" :description "Service Rendered" :extended-description ""))
  (persist (make-allsort "Procurement Transactions Import" "Item Description" :description "Item Description" :extended-description ""))
  (persist (make-allsort "Procurement Transactions Import" "Transaction Amount" :description "Transaction Amount" :extended-description ""))
  (persist (make-allsort "Procurement Transactions Import" "Transaction Date" :description "Transaction Date" :extended-description ""))
  (persist (make-allsort "Procurement Transactions Import" "Effective Start Date" :description "Effective Start Date" :extended-description ""))
  (persist (make-allsort "Procurement Transactions Import" "Effective End Date" :description "Effective End Date" :extended-description ""))
  (persist (make-allsort "Project Meeting Attendee Status" "Attended" :description "Attended" :extended-description ""))
  (persist (make-allsort "Project Meeting Attendee Status" "Not Attend" :description "Not Attend" :extended-description ""))
  (persist (make-allsort "Project Meeting Attendee Status" "Proxy" :description "Proxy" :extended-description ""))
  (persist (make-allsort "Race" "African" :description "African" :extended-description ""))
  (persist (make-allsort "Race" "Coloured" :description "Coloured" :extended-description ""))
  (persist (make-allsort "Race" "Indian" :description "Indian" :extended-description ""))
  (persist (make-allsort "Race" "White" :description "White" :extended-description ""))
  (persist (make-allsort "Reporting Period Status" "Open" :description "Open" :extended-description ""))
  (persist (make-allsort "Reporting Period Status" "Closed" :description "Closed" :extended-description ""))
  (persist (make-allsort "Supplier Address Type" "Postal Address" :description "Postal Address" :extended-description ""))
  (persist (make-allsort "Supplier Address Type" "Physical Address" :description "Physical Address" :extended-description ""))
  (persist (make-allsort "Suppliers Import" "Entity" :description "Entity" :extended-description ""))
  (persist (make-allsort "Suppliers Import" "Supplier Name" :description "Supplier Name" :extended-description ""))
  (persist (make-allsort "Suppliers Import" "Supplier Reference" :description "Supplier Reference" :extended-description ""))
  (persist (make-allsort "Suppliers Import" "Narrow Based BEE Classification" :description "Narrow Based BEE Classification" :extended-description ""))
  (persist (make-allsort "Suppliers Import" "Broad Based BEE Classification" :description "Broad Based BEE Classification" :extended-description ""))
  (persist (make-allsort "Suppliers Import" "HDSA Percentage" :description "HDSA Percentage" :extended-description ""))
  (persist (make-allsort "Suppliers Import" "Black Women Owned" :description "Black Women Owned" :extended-description ""))
  (persist (make-allsort "Suppliers Import" "Multinational" :description "Multinational" :extended-description ""))
  (persist (make-allsort "Suppliers Import" "Effective Start Date" :description "Effective Start Date" :extended-description ""))
  (persist (make-allsort "Suppliers Import" "Effective End Date" :description "Effective End Date" :extended-description ""))
  (persist (make-allsort "Termination Reasons" "" :description "" :extended-description ""))
  (persist (make-allsort "Termination Reasons" "Abscondment" :description "Abscondment" :extended-description ""))
  (persist (make-allsort "Termination Reasons" "Deceased" :description "Deceased" :extended-description ""))
  (persist (make-allsort "Termination Reasons" "Dismissal - Incapacity" :description "Dismissal - Incapacity" :extended-description ""))
  (persist (make-allsort "Termination Reasons" "Dismissal - Misconduct" :description "Dismissal - Misconduct" :extended-description ""))
  (persist (make-allsort "Termination Reasons" "Non-renewal of Contract" :description "Non-renewal of Contract" :extended-description ""))
  (persist (make-allsort "Termination Reasons" "Other" :description "Other" :extended-description ""))
  (persist (make-allsort "Termination Reasons" "Resignation" :description "Resignation" :extended-description ""))
  (persist (make-allsort "Termination Reasons" "Retirement" :description "Retirement" :extended-description ""))
  (persist (make-allsort "Termination Reasons" "Retrenchment" :description "Retrenchment" :extended-description ""))
  (persist (make-allsort "Termination Reasons" "Transfer" :description "Transfer" :extended-description ""))
  (persist (make-allsort "Undertaking" "ABET" :description "ABET" :extended-description ""))
  (persist (make-allsort "Undertaking" "ABET Community" :description "ABET Community" :extended-description ""))
  (persist (make-allsort "Undertaking" "Bursaries" :description "Bursaries" :extended-description ""))
  (persist (make-allsort "Undertaking" "Career Progression Plans" :description "Career Progression Plans" :extended-description ""))
  (persist (make-allsort "Undertaking" "Core Business Skills Training" :description "Core Business Skills Training" :extended-description ""))
  (persist (make-allsort "Undertaking" "Employment Equity" :description "Employment Equity" :extended-description ""))
  (persist (make-allsort "Undertaking" "Establishment of Future Forum" :description "Establishment of Future Forum" :extended-description ""))
  (persist (make-allsort "Undertaking" "Financial Provision - Downscaling & Retrenchment" :description "Financial Provision - Downscaling & Retrenchment" :extended-description ""))
  (persist (make-allsort "Undertaking" "Financial Provision - HRD" :description "Financial Provision - HRD" :extended-description ""))
  (persist (make-allsort "Undertaking" "Financial Provision - LED" :description "Financial Provision - LED" :extended-description ""))
  (persist (make-allsort "Undertaking" "HDSA In Management" :description "HDSA In Management" :extended-description ""))
  (persist (make-allsort "Undertaking" "Housing Strategy" :description "Housing Strategy" :extended-description ""))
  (persist (make-allsort "Undertaking" "Internships" :description "Internships" :extended-description ""))
  (persist (make-allsort "Undertaking" "Learnerships" :description "Learnerships" :extended-description ""))
  (persist (make-allsort "Undertaking" "Local Economic Development" :description "Local Economic Development" :extended-description ""))
  (persist (make-allsort "Undertaking" "Local Recruitment" :description "Local Recruitment" :extended-description ""))
  (persist (make-allsort "Undertaking" "Mechanisms to Ameliorate Socio-Economic Impact" :description "Mechanisms to Ameliorate Socio-Economic Impact" :extended-description ""))
  (persist (make-allsort "Undertaking" "Mechanisms to Avoid Job Losses" :description "Mechanisms to Avoid Job Losses" :extended-description ""))
  (persist (make-allsort "Undertaking" "Mentoring" :description "Mentoring" :extended-description ""))
  (persist (make-allsort "Undertaking" "Nutrition" :description "Nutrition" :extended-description ""))
  (persist (make-allsort "Undertaking" "Portable Skills Training" :description "Portable Skills Training" :extended-description ""))
  (persist (make-allsort "Undertaking" "Preferential Procurement - HDSA" :description "Preferential Procurement - HDSA" :extended-description ""))
  (persist (make-allsort "Undertaking" "Preferential Procurement - Local" :description "Preferential Procurement - Local" :extended-description ""))
  (persist (make-allsort "Undertaking" "Provision of Alternative Solutions" :description "Provision of Alternative Solutions" :extended-description ""))
  (persist (make-allsort "Undertaking" "Skills Development" :description "Skills Development" :extended-description ""))
  (persist (make-allsort "Undertaking" "SLP Communication Strategy" :description "SLP Communication Strategy" :extended-description ""))
  (persist (make-allsort "Undertaking" "SMME Mentoring" :description "SMME Mentoring" :extended-description ""))
  (persist (make-allsort "Undertaking" "Women In Mining" :description "Women In Mining" :extended-description ""))
  (persist (make-allsort "Undertaking" "Workforce Ramp Up" :description "Workforce Ramp Up" :extended-description ""))
  (persist (make-allsort "User Preferences" "Last Context" :description "Last Context" :extended-description ""))
  (persist (make-allsort "User Preferences" "Grid Lines" :description "Grid Lines" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "A - African" :description "A - African" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "A - Coloured" :description "A - Coloured" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "A - Indian" :description "A - Indian" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "A - White" :description "A - White" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "B - African" :description "B - African" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "B - Coloured" :description "B - Coloured" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "B - Indian" :description "B - Indian" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "B - White" :description "B - White" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "C - African" :description "C - African" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "C - Coloured" :description "C - Coloured" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "C - Indian" :description "C - Indian" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "C - White" :description "C - White" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "D - African" :description "D - African" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "D - Coloured" :description "D - Coloured" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "D - Indian" :description "D - Indian" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "D - White" :description "D - White" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "E - African" :description "E - African" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "E - Coloured" :description "E - Coloured" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "E - Indian" :description "E - Indian" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "E - White" :description "E - White" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "F - African" :description "F - African" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "F - Coloured" :description "F - Coloured" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "F - Indian" :description "F - Indian" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "F - White" :description "F - White" :extended-description ""))
  (persist (make-allsort "Women In Mining Target" "Projected Core Mining Positions" :description "Projected Core Mining Positions" :extended-description ""))

  (persist (make-allsort "Import Type" "Biographical" :description "Biographical" :extended-description "Biographical"))
  (persist (make-allsort "Import Type" "Job Titles" :description "Job Titles" :extended-description "Job Titles"))
  (persist (make-allsort "Import Type" "Training Interventions" :description "Training Interventions" :extended-description "Training Interventions"))
  (persist (make-allsort "Import Type" "Employee Trainging Interventions" :description "Employee Trainging Interventions" :extended-description "Employee Trainging Interventions"))
  (persist (make-allsort "Import Type" "Suppliers" :description "Suppliers" :extended-description "Suppliers"))
  (persist (make-allsort "Import Type" "Suppliers with Branch" :description "Suppliers with Branch" :extended-description "Suppliers with Branch"))
  (persist (make-allsort "Import Type" "Suppliers Branch" :description "Suppliers Branch" :extended-description "Suppliers Branch"))
  (persist (make-allsort "Import Type" "Procurement Transactions" :description "Procurement Transactions" :extended-description "Procurement Transactions"))

  (persist (make-allsort "Import Type - Job Titles" 'entity :description "Entity" :extended-description ""))
  (persist (make-allsort "Import Type - Job Titles" 'job-title :description "Job Title" :extended-description ""))
  (persist (make-allsort "Import Type - Job Titles" 'decription :description "Description" :extended-description ""))
  (persist (make-allsort "Import Type - Job Titles" 'core-mining :description "Core Mining (Y/N)" :extended-description ""))
  (persist (make-allsort "Import Type - Job Titles" 'occupational-level :description "Occupational Level" :extended-description ""))

  (persist (make-allsort "Import Type - Biographical" 'entity :description "Entity" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'employee-number :description "Employee Number" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'id-number :description "ID Number" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'surname :description "Surname" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'name :description "Name" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'gender :description "Gender" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'race :description "Race" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'nationality :description "Nationality" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'occupational-category :description "Occupational Category" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'occupational-level :description "Occupational Level" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'disabled :description "Disabled" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'employment-type :description "Employment Type" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'job-title :description "Job Title" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'educational-level :description "Educational Level" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'housing-status :description "Housing Status" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'postal-address-line :description "Postal Address Line" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'postal-address-country :description "Postal Address Country" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'postal-address-province :description "Postal Address Province" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'postal-address-town :description "Postal Address Town" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'physical-address-line :description "Physical Address Line" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'physical-address-country :description "Physical Address Country" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'physical-address-province :description "Physical Address Province" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'physical-address-town :description "Physical Address Town" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'home-address-line :description "Home Address Line" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'home-address-country :description "Home Address Country" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'home-address-province :description "Home Address Province" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'home-address-town :description "Home Address Town" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'date-of-birth :description "Date of Birth" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'date-of-engagement :description "Date of Engagement" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'date-of-termination :description "Date of Termination" :extended-description ""))
  (persist (make-allsort "Import Type - Biographical" 'termination-reason :description "Termination Reason" :extended-description ""))

  (persist (make-allsort "Import Type - Training Interventions" 'entity :description "Entity" :extended-description ""))
  (persist (make-allsort "Import Type - Training Interventions" 'category :description "Category" :extended-description ""))
  (persist (make-allsort "Import Type - Training Interventions" 'course-name :description "Course Name" :extended-description ""))
  (persist (make-allsort "Import Type - Training Interventions" 'mentorship-p :description "Mentorship (Y/N)" :extended-description ""))
  (persist (make-allsort "Import Type - Training Interventions" 'entry-level :description "Entry Level" :extended-description ""))
  (persist (make-allsort "Import Type - Training Interventions" 'accredited-p :description "Accredited (Y/N)" :extended-description ""))
  (persist (make-allsort "Import Type - Training Interventions" 'length :description "Length of Course" :extended-description ""))

  (persist (make-allsort "Import Type - Employee Training Interventions" 'entity :description "Entity" :extended-description ""))
  (persist (make-allsort "Import Type - Employee Training Interventions" 'employee-number :description "Employee Number" :extended-description ""))
  (persist (make-allsort "Import Type - Employee Training Interventions" 'training-intervention :description "Course Name" :extended-description ""))
  (persist (make-allsort "Import Type - Employee Training Interventions" 'mentor :description "Mentor Employee Number" :extended-description ""))
  (persist (make-allsort "Import Type - Employee Training Interventions" 'status :description "Status" :extended-description ""))
  (persist (make-allsort "Import Type - Employee Training Interventions" 'start-date :description "Start Date" :extended-description ""))
  (persist (make-allsort "Import Type - Employee Training Interventions" 'end-date :description "End Date" :extended-description ""))


  (persist (make-allsort "Import Type - Suppliers" 'entity :description "Entity" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers" 'supplier-name :description "Supplier Name" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers" 'multinational :description "Multinational (Y/N)" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers" 'narrow-based-bee-classification :description "Narrow Based BEE Classification" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers" 'broad-based-bee-classification :description "Broad Based BEE Classification" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers" 'hdsa-percetage :description "HDSA %" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers" 'black-women-owned :description "Black Woman Owned %" :extended-description ""))
  
  (persist (make-allsort "Import Type - Suppliers With Branch" 'entity :description "Entity" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'supplier-name :description "Supplier Name" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'branch-name :description "Branch Name" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'postal-address-line :description "Postal Address Line" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'postal-address-country :description "Postal Address Country" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'postal-address-province :description "Postal Address Province" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'postal-address-town :description "Postal Address Town" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'physical-address-line :description "Physical Address Line" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'physical-address-country :description "Physical Address Country" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'physical-address-province :description "Physical Address Province" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'physical-address-town :description "Physical Address Town" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'contact-name :description "Contact Person" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'telephone-number :description "Contact Number" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'facsimile-number :description "Contact Fax Number" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'email-address :description "Contact Email" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'multinational :description "Multinational (Y/N)" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'narrow-based-bee-classification :description "Narrow Based BEE Classification" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'broad-based-bee-classification :description "Broad Based BEE Classification" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'hdsa-percetage :description "HDSA %" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers With Branch" 'black-women-owned :description "Black Woman Owned %" :extended-description ""))

  (persist (make-allsort "Import Type - Suppliers Branch" 'entity :description "Entity" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers Branch" 'supplier-name :description "Supplier Name" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers Branch" 'branch-name :description "Branch Name" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers Branch" 'postal-address-line :description "Postal Address Line" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers Branch" 'postal-address-country :description "Postal Address Country" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers Branch" 'postal-address-province :description "Postal Address Province" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers Branch" 'postal-address-town :description "Postal Address Town" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers Branch" 'physical-address-line :description "Physical Address Line" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers Branch" 'physical-address-country :description "Physical Address Country" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers Branch" 'physical-address-province :description "Physical Address Province" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers Branch" 'physical-address-town :description "Physical Address Town" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers Branch" 'contact-name :description "Contact Person" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers Branch" 'telephone-number :description "Contact Number" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers Branch" 'facsimile-number :description "Contact Fax Number" :extended-description ""))
  (persist (make-allsort "Import Type - Suppliers Branch" 'email-address :description "Contact Email" :extended-description ""))

  (persist (make-allsort "Import Type - Procurement Transactions" 'entity :description "Entity" :extended-description ""))
  (persist (make-allsort "Import Type - Procurement Transactions" 'supplier :description "Supplier Name" :extended-description ""))
  (persist (make-allsort "Import Type - Procurement Transactions" 'branch-name :description "Branch Name" :extended-description ""))
  (persist (make-allsort "Import Type - Procurement Transactions" 'transaction-reference :description "Transaction Reference" :extended-description ""))
  (persist (make-allsort "Import Type - Procurement Transactions" 'discretionary-spend :description "Discretionary Spend (Y/N)" :extended-description ""))
  (persist (make-allsort "Import Type - Procurement Transactions" 'service-rendered :description "Service Rendered" :extended-description ""))
  (persist (make-allsort "Import Type - Procurement Transactions" 'item-description :description "Item Description" :extended-description ""))
  (persist (make-allsort "Import Type - Procurement Transactions" 'transaction-amount :description "Transaction Amount" :extended-description ""))
  (persist (make-allsort "Import Type - Procurement Transactions" 'transaction-date :description "Transaction Date" :extended-description ""))
 
  (persist (make-allsort "Guess" "Yes" :description "Yes" :extended-description ""))
  (persist (make-allsort "Guess" "No" :description "No" :extended-description ""))
  )
#|(defmethod persist ((doc allsort) &key)
(store-doc (allsorts-collection) doc))|#
