(in-package :dyb)

(defclass allsort (doc)
  ((sort :initarg :sort 
         :initform nil
         :key t)
   (sort-value :initarg :sort-value 
               :initform nil
               :accessor sort-value
               :key t)
   (sort-order :initarg :sort-order 
               :initform nil)   
   (alternate-sort-order :initarg :alternate-sort-order 
                         :initform nil)
   (aa-sort-order :initarg :aa-sort-order 
                  :initform nil)
   (description :initarg :description 
                :initform nil)
   (extended-description :initarg :extended-description 
                         :initform nil))
  (:metaclass storable-versioned-class)
  (:default-initargs :doc-type "allsort"))

(defun allsorts-collection ()
  (get-collection (system-db) "allsorts"))

(defun allsorts ()
  (docs (allsorts-collection)))

(defmethod doc-collection ((doc allsort))
                                        ;(break "shit?")
  (allsorts-collection))

(defun make-allsort (sort sort-value &key
                     sort-order alternate-sort-order
                     aa-sort-order description
                     extended-description)
  (make-instance 'allsort
                 :doc-type "allsort" 
                 :sort sort
                 :sort-order sort-order
                 :sort-value sort-value
                 :alternate-sort-order alternate-sort-order
                 :aa-sort-order aa-sort-order
                 :description description
                 :extended-description extended-description))

(defun get-allsort (sort value)
  (get-doc (allsorts-collection) 
           (list sort value)))

(defun find-allsorts (sort)
  (find-docs 'list
             (lambda (doc)
               (string-equal (get-val doc 'sort) sort))
             (allsorts-collection)))

(defun find-allsorts-for-select (sort)
  (let ((docs (find-docs 'list
                         (lambda (doc)
                           (and (string-equal (get-val doc 'sort) sort)
                                (string-not-equal (get-val doc 'doc-status) "superseded")))
                         (allsorts-collection)))
        (data))
    (dolist (doc docs)
      (setf data (append data (list (list (get-val doc 'sort-value)
                                          (get-val doc 'description))))))
    data))

(defun get-sorted-allsorts (sort)
  (let ((docs (find-docs 'list
                         (lambda (doc)
                           (and (string-equal (get-val doc 'sort) sort)
                                (string-not-equal (get-val doc 'doc-status) "superseded")))
                         (allsorts-collection)))
        (data))
    
    (dolist (doc docs)
      (setf data (append data (list (get-val doc 'sort-value)))))
    (sort  data #'STRING-LESSP)))

(defun find-allsorts-for-validation (sort)
  (let ((docs (find-docs 'list
                         (lambda (doc)
                           (and (string-equal (get-val doc 'sort) sort)
                                (string-not-equal (get-val doc 'doc-status) "superseded")))
                         (allsorts-collection)))
        (data))
    (dolist (doc docs)
      (setf data (append data (list (get-val doc 'sort-value)))))
    data))

(defun get-allsort-by-id (id)
  (get-doc (allsorts-collection) id
           :element 'xid))

(defgeneric match-allsorts (doc allsorts))

(defmethod match-allsorts (doc allsorts)
  (find (get-val doc 'xid) allsorts))

(add-collection (system-db) "allsorts" 
                :collection-class 'dyb-collection)

(when (= (length (allsorts)) 0)
  
  (persist (make-allsort "Gender" "Female" :description "Female" :extended-description ""))
  (persist (make-allsort "Gender" "Male" :description "Male" :extended-description ""))

  (persist (make-allsort "Nationality" "Afghan" :description "Afghan" :extended-description ""))
  (persist (make-allsort "Nationality" "Albanian" :description "Albanian" :extended-description ""))
  (persist (make-allsort "Nationality" "Algerian" :description "Algerian" :extended-description ""))
  (persist (make-allsort "Nationality" "American" :description "American" :extended-description ""))
  (persist (make-allsort "Nationality" "Andorran" :description "Andorran" :extended-description ""))
  (persist (make-allsort "Nationality" "Angolan" :description "Angolan" :extended-description ""))
  (persist (make-allsort "Nationality" "Antiguans" :description "Antiguans" :extended-description ""))
  (persist (make-allsort "Nationality" "Argentinean" :description "Argentinean" :extended-description ""))
  (persist (make-allsort "Nationality" "Armenian" :description "Armenian" :extended-description ""))
  (persist (make-allsort "Nationality" "Australian" :description "Australian" :extended-description ""))
  (persist (make-allsort "Nationality" "Austrian" :description "Austrian" :extended-description ""))
  (persist (make-allsort "Nationality" "Azerbaijani" :description "Azerbaijani" :extended-description ""))
  (persist (make-allsort "Nationality" "Bahamian" :description "Bahamian" :extended-description ""))
  (persist (make-allsort "Nationality" "Bahraini" :description "Bahraini" :extended-description ""))
  (persist (make-allsort "Nationality" "Bangladeshi" :description "Bangladeshi" :extended-description ""))
  (persist (make-allsort "Nationality" "Barbadian" :description "Barbadian" :extended-description ""))
  (persist (make-allsort "Nationality" "Barbudans" :description "Barbudans" :extended-description ""))
  (persist (make-allsort "Nationality" "Batswana" :description "Batswana" :extended-description ""))
  (persist (make-allsort "Nationality" "Belarusian" :description "Belarusian" :extended-description ""))
  (persist (make-allsort "Nationality" "Belgian" :description "Belgian" :extended-description ""))
  (persist (make-allsort "Nationality" "Belizean" :description "Belizean" :extended-description ""))
  (persist (make-allsort "Nationality" "Beninese" :description "Beninese" :extended-description ""))
  (persist (make-allsort "Nationality" "Bhutanese" :description "Bhutanese" :extended-description ""))
  (persist (make-allsort "Nationality" "Bolivian" :description "Bolivian" :extended-description ""))
  (persist (make-allsort "Nationality" "Bosnian" :description "Bosnian" :extended-description ""))
  (persist (make-allsort "Nationality" "Brazilian" :description "Brazilian" :extended-description ""))
  (persist (make-allsort "Nationality" "British" :description "British" :extended-description ""))
  (persist (make-allsort "Nationality" "Bruneian" :description "Bruneian" :extended-description ""))
  (persist (make-allsort "Nationality" "Bulgarian" :description "Bulgarian" :extended-description ""))
  (persist (make-allsort "Nationality" "Burkinabe" :description "Burkinabe" :extended-description ""))
  (persist (make-allsort "Nationality" "Burmese" :description "Burmese" :extended-description ""))
  (persist (make-allsort "Nationality" "Burundian" :description "Burundian" :extended-description ""))
  (persist (make-allsort "Nationality" "Cambodian" :description "Cambodian" :extended-description ""))
  (persist (make-allsort "Nationality" "Cameroonian" :description "Cameroonian" :extended-description ""))
  (persist (make-allsort "Nationality" "Canadian" :description "Canadian" :extended-description ""))
  (persist (make-allsort "Nationality" "Cape Verdean" :description "Cape Verdean" :extended-description ""))
  (persist (make-allsort "Nationality" "Central African" :description "Central African" :extended-description ""))
  (persist (make-allsort "Nationality" "Chadian" :description "Chadian" :extended-description ""))
  (persist (make-allsort "Nationality" "Chilean" :description "Chilean" :extended-description ""))
  (persist (make-allsort "Nationality" "Chinese" :description "Chinese" :extended-description ""))
  (persist (make-allsort "Nationality" "Colombian" :description "Colombian" :extended-description ""))
  (persist (make-allsort "Nationality" "Comoran" :description "Comoran" :extended-description ""))
  (persist (make-allsort "Nationality" "Congolese" :description "Congolese" :extended-description ""))
  (persist (make-allsort "Nationality" "Costa Rican" :description "Costa Rican" :extended-description ""))
  (persist (make-allsort "Nationality" "Croatian" :description "Croatian" :extended-description ""))
  (persist (make-allsort "Nationality" "Cuban" :description "Cuban" :extended-description ""))
  (persist (make-allsort "Nationality" "Cypriot" :description "Cypriot" :extended-description ""))
  (persist (make-allsort "Nationality" "Czech" :description "Czech" :extended-description ""))
  (persist (make-allsort "Nationality" "Danish" :description "Danish" :extended-description ""))
  (persist (make-allsort "Nationality" "Djibouti" :description "Djibouti" :extended-description ""))
  (persist (make-allsort "Nationality" "Dominican" :description "Dominican" :extended-description ""))
  (persist (make-allsort "Nationality" "Dutch" :description "Dutch" :extended-description ""))
  (persist (make-allsort "Nationality" "East Timorese" :description "East Timorese" :extended-description ""))
  (persist (make-allsort "Nationality" "Ecuadorean" :description "Ecuadorean" :extended-description ""))
  (persist (make-allsort "Nationality" "Egyptian" :description "Egyptian" :extended-description ""))
  (persist (make-allsort "Nationality" "Emirian" :description "Emirian" :extended-description ""))
  (persist (make-allsort "Nationality" "Equatorial Guinean" :description "Equatorial Guinean" :extended-description ""))
  (persist (make-allsort "Nationality" "Eritrean" :description "Eritrean" :extended-description ""))
  (persist (make-allsort "Nationality" "Estonian" :description "Estonian" :extended-description ""))
  (persist (make-allsort "Nationality" "Ethiopian" :description "Ethiopian" :extended-description ""))
  (persist (make-allsort "Nationality" "Fijian" :description "Fijian" :extended-description ""))
  (persist (make-allsort "Nationality" "Filipino" :description "Filipino" :extended-description ""))
  (persist (make-allsort "Nationality" "Finnish" :description "Finnish" :extended-description ""))
  (persist (make-allsort "Nationality" "French" :description "French" :extended-description ""))
  (persist (make-allsort "Nationality" "Gabonese" :description "Gabonese" :extended-description ""))
  (persist (make-allsort "Nationality" "Gambian" :description "Gambian" :extended-description ""))
  (persist (make-allsort "Nationality" "Georgian" :description "Georgian" :extended-description ""))
  (persist (make-allsort "Nationality" "German" :description "German" :extended-description ""))
  (persist (make-allsort "Nationality" "Ghanaian" :description "Ghanaian" :extended-description ""))
  (persist (make-allsort "Nationality" "Greek" :description "Greek" :extended-description ""))
  (persist (make-allsort "Nationality" "Grenadian" :description "Grenadian" :extended-description ""))
  (persist (make-allsort "Nationality" "Guatemalan" :description "Guatemalan" :extended-description ""))
  (persist (make-allsort "Nationality" "Guinea-Bissauan" :description "Guinea-Bissauan" :extended-description ""))
  (persist (make-allsort "Nationality" "Guinean" :description "Guinean" :extended-description ""))
  (persist (make-allsort "Nationality" "Guyanese" :description "Guyanese" :extended-description ""))
  (persist (make-allsort "Nationality" "Haitian" :description "Haitian" :extended-description ""))
  (persist (make-allsort "Nationality" "Herzegovinian" :description "Herzegovinian" :extended-description ""))
  (persist (make-allsort "Nationality" "Honduran" :description "Honduran" :extended-description ""))
  (persist (make-allsort "Nationality" "Hungarian" :description "Hungarian" :extended-description ""))
  (persist (make-allsort "Nationality" "I-Kiribati" :description "I-Kiribati" :extended-description ""))
  (persist (make-allsort "Nationality" "Icelander" :description "Icelander" :extended-description ""))
  (persist (make-allsort "Nationality" "Indian" :description "Indian" :extended-description ""))
  (persist (make-allsort "Nationality" "Indonesian" :description "Indonesian" :extended-description ""))
  (persist (make-allsort "Nationality" "Iranian" :description "Iranian" :extended-description ""))
  (persist (make-allsort "Nationality" "Iraqi" :description "Iraqi" :extended-description ""))
  (persist (make-allsort "Nationality" "Irish" :description "Irish" :extended-description ""))
  (persist (make-allsort "Nationality" "Israeli" :description "Israeli" :extended-description ""))
  (persist (make-allsort "Nationality" "Italian" :description "Italian" :extended-description ""))
  (persist (make-allsort "Nationality" "Ivorian" :description "Ivorian" :extended-description ""))
  (persist (make-allsort "Nationality" "Jamaican" :description "Jamaican" :extended-description ""))
  (persist (make-allsort "Nationality" "Japanese" :description "Japanese" :extended-description ""))
  (persist (make-allsort "Nationality" "Jordanian" :description "Jordanian" :extended-description ""))
  (persist (make-allsort "Nationality" "Kazakhstani" :description "Kazakhstani" :extended-description ""))
  (persist (make-allsort "Nationality" "Kenyan" :description "Kenyan" :extended-description ""))
  (persist (make-allsort "Nationality" "Kittian and Nevisian" :description "Kittian and Nevisian" :extended-description ""))
  (persist (make-allsort "Nationality" "Kuwaiti" :description "Kuwaiti" :extended-description ""))
  (persist (make-allsort "Nationality" "Kyrgyz" :description "Kyrgyz" :extended-description ""))
  (persist (make-allsort "Nationality" "Laotian" :description "Laotian" :extended-description ""))
  (persist (make-allsort "Nationality" "Latvian" :description "Latvian" :extended-description ""))
  (persist (make-allsort "Nationality" "Lebanese" :description "Lebanese" :extended-description ""))
  (persist (make-allsort "Nationality" "Liberian" :description "Liberian" :extended-description ""))
  (persist (make-allsort "Nationality" "Libyan" :description "Libyan" :extended-description ""))
  (persist (make-allsort "Nationality" "Liechtensteiner" :description "Liechtensteiner" :extended-description ""))
  (persist (make-allsort "Nationality" "Lithuanian" :description "Lithuanian" :extended-description ""))
  (persist (make-allsort "Nationality" "Luxembourger" :description "Luxembourger" :extended-description ""))
  (persist (make-allsort "Nationality" "Macedonian" :description "Macedonian" :extended-description ""))
  (persist (make-allsort "Nationality" "Malagasy" :description "Malagasy" :extended-description ""))
  (persist (make-allsort "Nationality" "Malawian" :description "Malawian" :extended-description ""))
  (persist (make-allsort "Nationality" "Malaysian" :description "Malaysian" :extended-description ""))
  (persist (make-allsort "Nationality" "Maldivan" :description "Maldivan" :extended-description ""))
  (persist (make-allsort "Nationality" "Malian" :description "Malian" :extended-description ""))
  (persist (make-allsort "Nationality" "Maltese" :description "Maltese" :extended-description ""))
  (persist (make-allsort "Nationality" "Marshallese" :description "Marshallese" :extended-description ""))
  (persist (make-allsort "Nationality" "Mauritanian" :description "Mauritanian" :extended-description ""))
  (persist (make-allsort "Nationality" "Mauritian" :description "Mauritian" :extended-description ""))
  (persist (make-allsort "Nationality" "Mexican" :description "Mexican" :extended-description ""))
  (persist (make-allsort "Nationality" "Micronesian" :description "Micronesian" :extended-description ""))
  (persist (make-allsort "Nationality" "Moldovan" :description "Moldovan" :extended-description ""))
  (persist (make-allsort "Nationality" "Monacan" :description "Monacan" :extended-description ""))
  (persist (make-allsort "Nationality" "Mongolian" :description "Mongolian" :extended-description ""))
  (persist (make-allsort "Nationality" "Moroccan" :description "Moroccan" :extended-description ""))
  (persist (make-allsort "Nationality" "Mosotho" :description "Mosotho" :extended-description ""))
  (persist (make-allsort "Nationality" "Motswana" :description "Motswana" :extended-description ""))
  (persist (make-allsort "Nationality" "Mozambican" :description "Mozambican" :extended-description ""))
  (persist (make-allsort "Nationality" "Namibian" :description "Namibian" :extended-description ""))
  (persist (make-allsort "Nationality" "Nauruan" :description "Nauruan" :extended-description ""))
  (persist (make-allsort "Nationality" "Nepalese" :description "Nepalese" :extended-description ""))
  (persist (make-allsort "Nationality" "New Zealander" :description "New Zealander" :extended-description ""))
  (persist (make-allsort "Nationality" "Nicaraguan" :description "Nicaraguan" :extended-description ""))
  (persist (make-allsort "Nationality" "Nigerian" :description "Nigerian" :extended-description ""))
  (persist (make-allsort "Nationality" "Nigerien" :description "Nigerien" :extended-description ""))
  (persist (make-allsort "Nationality" "North Korean" :description "North Korean" :extended-description ""))
  (persist (make-allsort "Nationality" "Northern Irish" :description "Northern Irish" :extended-description ""))
  (persist (make-allsort "Nationality" "Norwegian" :description "Norwegian" :extended-description ""))
  (persist (make-allsort "Nationality" "Omani" :description "Omani" :extended-description ""))
  (persist (make-allsort "Nationality" "Pakistani" :description "Pakistani" :extended-description ""))
  (persist (make-allsort "Nationality" "Palauan" :description "Palauan" :extended-description ""))
  (persist (make-allsort "Nationality" "Panamanian" :description "Panamanian" :extended-description ""))
  (persist (make-allsort "Nationality" "Papua New Guinean" :description "Papua New Guinean" :extended-description ""))
  (persist (make-allsort "Nationality" "Paraguayan" :description "Paraguayan" :extended-description ""))
  (persist (make-allsort "Nationality" "Peruvian" :description "Peruvian" :extended-description ""))
  (persist (make-allsort "Nationality" "Polish" :description "Polish" :extended-description ""))
  (persist (make-allsort "Nationality" "Portuguese" :description "Portuguese" :extended-description ""))
  (persist (make-allsort "Nationality" "Qatari" :description "Qatari" :extended-description ""))
  (persist (make-allsort "Nationality" "Romanian" :description "Romanian" :extended-description ""))
  (persist (make-allsort "Nationality" "Russian" :description "Russian" :extended-description ""))
  (persist (make-allsort "Nationality" "Rwandan" :description "Rwandan" :extended-description ""))
  (persist (make-allsort "Nationality" "Saint Lucian" :description "Saint Lucian" :extended-description ""))
  (persist (make-allsort "Nationality" "Salvadoran" :description "Salvadoran" :extended-description ""))
  (persist (make-allsort "Nationality" "Samoan" :description "Samoan" :extended-description ""))
  (persist (make-allsort "Nationality" "San Marinese" :description "San Marinese" :extended-description ""))
  (persist (make-allsort "Nationality" "Sao Tomean" :description "Sao Tomean" :extended-description ""))
  (persist (make-allsort "Nationality" "Saudi" :description "Saudi" :extended-description ""))
  (persist (make-allsort "Nationality" "Scottish" :description "Scottish" :extended-description ""))
  (persist (make-allsort "Nationality" "Senegalese" :description "Senegalese" :extended-description ""))
  (persist (make-allsort "Nationality" "Serbian" :description "Serbian" :extended-description ""))
  (persist (make-allsort "Nationality" "Seychellois" :description "Seychellois" :extended-description ""))
  (persist (make-allsort "Nationality" "Sierra Leonean" :description "Sierra Leonean" :extended-description ""))
  (persist (make-allsort "Nationality" "Singaporean" :description "Singaporean" :extended-description ""))
  (persist (make-allsort "Nationality" "Slovakian" :description "Slovakian" :extended-description ""))
  (persist (make-allsort "Nationality" "Slovenian" :description "Slovenian" :extended-description ""))
  (persist (make-allsort "Nationality" "Solomon Islander" :description "Solomon Islander" :extended-description ""))
  (persist (make-allsort "Nationality" "Somali" :description "Somali" :extended-description ""))
  (persist (make-allsort "Nationality" "South African" :description "South African" :extended-description ""))
  (persist (make-allsort "Nationality" "South Korean" :description "South Korean" :extended-description ""))
  (persist (make-allsort "Nationality" "Spanish" :description "Spanish" :extended-description ""))
  (persist (make-allsort "Nationality" "Sri Lankan" :description "Sri Lankan" :extended-description ""))
  (persist (make-allsort "Nationality" "Sudanese" :description "Sudanese" :extended-description ""))
  (persist (make-allsort "Nationality" "Surinamer" :description "Surinamer" :extended-description ""))
  (persist (make-allsort "Nationality" "Swazi" :description "Swazi" :extended-description ""))
  (persist (make-allsort "Nationality" "Swedish" :description "Swedish" :extended-description ""))
  (persist (make-allsort "Nationality" "Swiss" :description "Swiss" :extended-description ""))
  (persist (make-allsort "Nationality" "Syrian" :description "Syrian" :extended-description ""))
  (persist (make-allsort "Nationality" "Taiwanese" :description "Taiwanese" :extended-description ""))
  (persist (make-allsort "Nationality" "Tajik" :description "Tajik" :extended-description ""))
  (persist (make-allsort "Nationality" "Tanzanian" :description "Tanzanian" :extended-description ""))
  (persist (make-allsort "Nationality" "Thai" :description "Thai" :extended-description ""))
  (persist (make-allsort "Nationality" "Togolese" :description "Togolese" :extended-description ""))
  (persist (make-allsort "Nationality" "Tongan" :description "Tongan" :extended-description ""))
  (persist (make-allsort "Nationality" "Trinidadian or Tobagonian" :description "Trinidadian or Tobagonian" :extended-description ""))
  (persist (make-allsort "Nationality" "Tunisian" :description "Tunisian" :extended-description ""))
  (persist (make-allsort "Nationality" "Turkish" :description "Turkish" :extended-description ""))
  (persist (make-allsort "Nationality" "Tuvaluan" :description "Tuvaluan" :extended-description ""))
  (persist (make-allsort "Nationality" "Ugandan" :description "Ugandan" :extended-description ""))
  (persist (make-allsort "Nationality" "Ukrainian" :description "Ukrainian" :extended-description ""))
  (persist (make-allsort "Nationality" "Uruguayan" :description "Uruguayan" :extended-description ""))
  (persist (make-allsort "Nationality" "Uzbekistani" :description "Uzbekistani" :extended-description ""))
  (persist (make-allsort "Nationality" "Venezuelan" :description "Venezuelan" :extended-description ""))
  (persist (make-allsort "Nationality" "Vietnamese" :description "Vietnamese" :extended-description ""))
  (persist (make-allsort "Nationality" "Welsh" :description "Welsh" :extended-description ""))
  (persist (make-allsort "Nationality" "Yemenite" :description "Yemenite" :extended-description ""))
  (persist (make-allsort "Nationality" "Zambian" :description "Zambian" :extended-description ""))
  (persist (make-allsort "Nationality" "Zimbabwean" :description "Zimbabwean" :extended-description ""))
  (persist (make-allsort "Race" "African" :description "African" :extended-description ""))
  (persist (make-allsort "Race" "Coloured" :description "Coloured" :extended-description ""))
  (persist (make-allsort "Race" "Indian" :description "Indian" :extended-description ""))
  (persist (make-allsort "Race" "White" :description "White" :extended-description ""))
  (persist (make-allsort "Reporting Period Status" "Open" :description "Open" :extended-description ""))
  (persist (make-allsort "Reporting Period Status" "Closed" :description "Closed" :extended-description ""))
  (persist (make-allsort "User Preferences" "Last Context" :description "Last Context" :extended-description ""))
  (persist (make-allsort "User Preferences" "Grid Lines" :description "Grid Lines" :extended-description ""))

  (persist (make-allsort "Guess" "Yes" :description "Yes" :extended-description ""))
  (persist (make-allsort "Guess" "No" :description "No" :extended-description ""))
  )
#|(defmethod persist ((doc allsort) &key)
(store-doc (allsorts-collection) doc))|#
